### ISSUE TITLE
Time Driver Crashing When Slowing to sub-0.12 speed

### ISSUE THREAD

**Issue by Donnie-Ice** [nasa/nos3#286] opened 2024-04-25 17:30 UTC
Happened on nos3#202 branch, Cryptolib vcid 4, Enabled telemetry, paused time driver, then slowed to sub-0.12.

**Comment by Donnie-Ice** [comment] 2024-04-25 17:48
Can recreate crash by just slowing to sub-0.12. No need to enable encryption, telem, or pause.

**Comment by msuder** [comment] 2024-10-28 14:42
The exception is caused by this line (time_driver.cpp, line 123):

`if ((_display_counter % (ticks_per_second/10)) == 0) { // only report about every 1/10th of a second`

When ticks_per_second is less than 10, the modulo part is 0 and so _display_counter % 0 gives divide by zero.

**Comment by jlucas9** [comment] 2024-10-29 20:40
Merged to `dev` in ^

**Closed by jlucas9** 2024-10-29 20:40 UTC
Labels: Bug
