### ISSUE TITLE
COSMOS5 GSW problem

### ISSUE THREAD

**Issue by Gonta01** [nasa/nos3#311] opened 2024-05-30 12:25 UTC
Tried to use COMSOS5 but while trying to send commands runtime error occurs.
![image](https://github.com/nasa/nos3/assets/127857320/0d39f799-4f13-4f7c-bed6-02af46ef50d7)

**Comment by jlucas9** [comment] 2024-06-19 19:41
Just walking through my steps to attempt to recreate:
* git checkout dev
* git submodule update --init --recursive
* git rev-parse --short HEAD
  * 9b56e75
* make prep
* In Igniter
  * Change GSW to `openc3`
  * Save
* make
  * Wait for build to complete and CPU utilization to settle down as OpenC3 COSMOS continues to process in the background
* make launch
  * Reorganize windows
  * Set OpenC3 cosmos password

Confirmed debug data being received in OpenC3 COSMOS CmdTlmServer:

![image](https://github.com/nasa/nos3/assets/6588622/9800fdbf-5615-4223-b889-74170b1219fe)


Manually send ARDUCAM_DEBUG CAM_NOOP_CC:

![image](https://github.com/nasa/nos3/assets/6588622/66202083-9fef-4105-b60a-9f5c9b356cd4)


I think it could have been that the CmdTlmServer was not connected when you tested originally. Let me know if you have any follow-ups to this!

**Comment by Gonta01** [comment] 2024-06-20 12:43
I tested with 1.7.0 release and the result is the following:
![image](https://github.com/nasa/nos3/assets/127857320/c7351748-e6be-4a66-9802-b60b1b26a7c5)
![image](https://github.com/nasa/nos3/assets/127857320/47a9dd51-d9a0-4c1c-a1f2-954fa9d6b466)

Tried to send command:
![image](https://github.com/nasa/nos3/assets/127857320/6f01c7aa-252a-46e5-9307-4acbd5101994)

**Comment by jlucas9** [comment] 2024-06-25 10:34
Looks like your interfaces didn't get created successfully in the CmdTlmServer. Can you `make stop-gsw` then do another `make prep` and `make` and see if it builds and attaches the OpenC3 plugin correctly the second round?

**Comment by jlucas9** [comment] 2024-07-23 11:28
Closing due to age, if this problem persists please re-open or file a new issue with your latest!

**Closed by jlucas9** 2024-07-23 11:28 UTC
Labels: Support
