### ISSUE TITLE
cant login with nos3 user

### ISSUE THREAD

**Issue by techsup93** [nasa/nos3#56] opened 2020-12-07 21:25 UTC
### **hi all
**I installed the NOS3 v1.05 according to the instructions below.**

----------------------------------------------------------------------------------------------

Installing
1  Open a terminal
2   Navigate to the desired location for the repository
3   Clone the repository git clone https://github.com/nasa/nos3.git
4   Clone the submodules git submodule init and git submodule update
5   Navigate to /nos3/deployment
6   Run vagrant up and wait to return to a prompt
-This can take anywhere from 20 minutes to hours depending on internet speeds and host PC specs
-The VM will reboot multiple times in order to finish install packages for you automatically so wait for that prompt!
7   Login to the nos3 user using the password nos3123! and get to work!
8   Try building and running following the instructions below

--------------------------------------------------------------------------------------------

**Everything went well until the sixth stage of installation
But
After Run command "vagrant up" and displaying the login page. The nos3 user is not displayed and I have to log in only with the vagrant user.
i uploaded pictures from vm.
how i can login with nos3 user?

Of course, I tried several times to logout and switch user, but there is no user with the nos3 username at all, There is only vagrant username.
thank you**

![VirtualBox_nos3_dev_1 05](https://user-images.githubusercontent.com/33166227/101406769-2429f200-38ef-11eb-9d1c-40d4b526c3ed.png)

![VirtualBox_nos3_dev_1 05 0_2](https://user-images.githubusercontent.com/33166227/101406886-4f144600-38ef-11eb-869e-89e0896da43c.png)

**Comment by efriesema** [comment] 2020-12-24 02:37
I'm in a similar place    command prompt where I ran vagrant up   it displayed the following so itlooks like something was wrong with ansible loading but there is no way to preload Ansible onto a windows machine
Windows version 10
VirtualBox  6.1 
Git 2.21.0.windows.1
Vagrant 2.2.14
==> dev: Mounting shared folders...
    dev: /vagrant => C:/Users/Ed/Source/Repos/NOS3/nos3/deployment
    dev: /tmp/filestore => C:/Users/Ed/Source/Repos/NOS3/nos3/deployment/nos3_filestore
==> dev: Running provisioner: ansible_local...
    dev: Installing Ansible...
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!


                add-apt-repository ppa:ansible/ansible -y &&                 apt-get update -y -qq &&                 DEBIAN_FRONTEND=noninteractive apt-get install -y -qq ansible --option "Dpkg::Options::=--force-confold"


Stdout from the command:

Reading package lists...


Stderr from the command:

E: Could not get lock /var/lib/apt/lists/lock - open (11: Resource temporarily unavailable)
E: Unable to lock directory /var/lib/apt/lists/

**Comment by hailhallmonitor** [comment] 2021-07-23 18:00
I am attempting to get past the vagrant login as well.

**Comment by satzguyz** [comment] 2022-05-21 13:44
The problem is incomplete installation. Try to destroy the vagrant and re-install again.

**Comment by jlucas9** [comment] 2022-09-15 11:34
Closing issue due to age.
Please create a new issue if this problem remains.

**Closed by jlucas9** 2022-09-15 11:34 UTC
